name: yugomuzej
description: "Yugomuzej"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  audioplayers: ^6.0.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_widget_from_html: ^0.15.0
  go_router: ^13.2.4
  provider: ^6.1.2
  sized_context: ^1.0.0+4
  url_launcher: ^6.2.6
  video_player: ^2.8.6
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/_assets/
    - assets/home/
    - assets/about/
    - assets/about/menu/
    - assets/_assets/images/
    - assets/_assets/images/main_exhibition/
    - assets/main_exibition/
    - assets/main_exibition/menu/
    - assets/exhibitions/
    - assets/exhibitions/menu/
    - assets/exhibitions/01/
    - assets/exhibitions/02/
    - assets/exhibitions/03/
    - assets/i_did_this/
    - assets/i_did_this/menu/
    - assets/souvenires/
    - assets/souvenires/menu/
    - assets/author/
    - assets/author/menu/
    - assets/kontakt/menu/
    - assets/video/
    - assets/video/menu/
    - assets/shop/
    - assets/shop/menu/
    - assets/shop/menu/drawings/
    - assets/shop/drawings/
    - assets/shop/souvenires/
    - assets/desktop/
    - assets/desktop/menu/
    - assets/desktop/pics/
    - assets/webteam/menu/
    - locales/

  fonts:
    - family: Arial
      fonts:
        - asset: assets/_assets/fonts/arial/ARIAL.TTF
        - asset: assets/_assets/fonts/arial/ARIALBD.TTF
          # style: bold
    - family: ArialBlack
      fonts:
        - asset: assets/_assets/fonts/arial/ARIBLK.TTF
